import type { Metadata } from 'next';
import { Sancreek } from 'next/font/google';
import Image from 'next/image';
import './globals.css';
import Link from 'next/link';

const sancreek = Sancreek({
  variable: '--font-sancreek',
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sancreek.variable} mt-4 bg-primary`}>
        <nav>
          <ul className="font-display nav-list flex justify-around bg-primary  border-t-1 border-white border-b-1 border-white">
            <li>
              <Link href="/">
                <Image src="/logo.svg" alt="logo" width={100} height={100} />
              </Link>
            </li>
            <li>About</li>
            <li>
              <Link href="/content">Content</Link>
            </li>
            <li>Resumes</li>
            <li>Contact</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
